name: Generate GitHub Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Generate snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Krish2843
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=%2300FF88&color_dots=%230D1117,%2300FF88,%2300E5FF,%239B59FF,%23FFFFFF

      - name: Publish snake
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
